# Generated by Django 4.1.5 on 2023-01-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='fullname12',
            field=models.CharField(default='12', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(default='12', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example',
            name='emp_code',
            field=models.CharField(default='12', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example',
            name='fullname123',
            field=models.CharField(default='12', max_length=500),
            preserve_default=False,
        ),
    ]
